spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8080

